### ISSUE TITLE
Allow window resizing

### ISSUE THREAD

**Issue by kououken** [bgoldbeck/rogue-two#10]
Now that the map size is no longer tied to the window size, it should be possible to allow resizing of the window.

**Comment by kououken** [comment]
Created resize functions for GameManager, Camera and HUD components, and had them be called whenever the Application detects a screen size change.

**Comment by bgoldbeck** [comment]
Should be handled by events, the Application.cs shouldn't have dependencies based on what is literally in a particular game. This would help with re-usability and maintainability.

**Comment by bgoldbeck** [comment]
https://github.com/bgoldbeck/rogue-two/commit/d3de5a6a347a002f24983effc3dcc5b1b2bb31be Refactored to use OnResize Events.
