### ISSUE TITLE
Passing String as a reference.

### ISSUE THREAD

**Issue by DanielRBramblett** [bgoldbeck/rogue-two#2]
In the MonsterGenerator class, a single string was used to pass a string by reference. For some reason, using a String object doesn't fix this issue. Using the keywords "out" or "ref" cause issues with other aspects of the code. 
This issue doesn't create a bug but should be optimized to more proper code since what is being used is a work around.

**Comment by bgoldbeck** [comment]
You should consider passing the StringBuilder class to the method and appending to it within the function.
