### ISSUE TITLE
Code duplication in the Player and Enemy components.

### ISSUE THREAD

**Issue by bgoldbeck** [bgoldbeck/rogue-two#5]
**Is your feature request related to a problem? Please describe.**
There is code duplication in the enemy and player components. The move function between the two classes are extremely similar.

**Describe the solution you'd like**
The duplicate code should be pushed up the heirarchy to the Actor component.

**Comment by DanielRBramblett** [comment]
There is slight differences between the enemy and player. For example, the player can damage all other damageable objects while the enemies can only damage the player. 
Also, for the player, all the other types of collisions that we might have will have to go in the move() method while the enemies or NPCs should not be effected by these other events.

**Comment by bgoldbeck** [comment]
slight differences still means 98% code duplication

**Comment by DanielRBramblett** [comment]
The only solution I can see that will allow you to push this move() method up to the Actor class is making one of the parameters of the method another abstract method to handle collision cases.

**Comment by DanielRBramblett** [comment]
I created a new branch called AbstractActor to test out how I would clean the code up. Is this what you where thinking?

**Comment by bgoldbeck** [comment]
see https://github.com/bgoldbeck/rogue-two/commit/a9c1ef81cb50f6408f495b0f434951f8caae7512 and https://github.com/bgoldbeck/rogue-two/commit/abbe5cd081ab9e3bc7d9786b1adeaa29e1c7203e
