### ISSUE TITLE
Enemy component can be made smaller.

### ISSUE THREAD

**Issue by bgoldbeck** [bgoldbeck/rogue-two#7]
**Is your feature request related to a problem? Please describe.**
The enemy component is getting large. We want the components to have clear precise responsibilities and be reasonably small, if possible.

**Describe the solution you'd like**
I propose a new component to be added on to enemy game objects called "Aggro". It would be the responsibility of the aggro component to search for the player and determine if they should be targeted.

**Comment by DanielRBramblett** [comment]
Since we are moving the move() method up to the Actor class, the Enemy component might not be too large to contain search and targeting of the player. Thoughts?
