### ISSUE TITLE
AI Pathfinding

### ISSUE THREAD

**Issue by kououken** [bgoldbeck/rogue-two#9]
Enemies should use rudimentary path-finding to approach/track the player. One possibility is use Dijkstra's algorithm to generate the shortest path to the player and move in that direction. I've already implemented this for a "programming mazes" book I got, so whoever wants to do this can borrow it if they want.

**Comment by bgoldbeck** [comment]
A* Algorithm mostly implemented feature in https://github.com/bgoldbeck/rogue-two/commit/1f1b76ab4fed3fb99107266d23de3d97143e94b6
